spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true

app.s3.bucket=hackathon-data-289140050770
app.s3.prefix=Challenge 1 ? Build Bundesliga Wrapped/

spring.cloud.aws.region.static=eu-central-1
spring.cloud.aws.s3.enabled=true